2023-10-13 18:36:52.641 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 18:36:52.655 [info] [Error - 18:36:52] Server initialization failed.
2023-10-13 18:36:52.655 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.655 [info] [Info  - 18:36:52] Connection to server got closed. Server will restart.
2023-10-13 18:36:52.655 [info] true
2023-10-13 18:36:52.655 [info] [Error - 18:36:52] Python Jedi client: couldn't create connection to server.
2023-10-13 18:36:52.655 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.744 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 18:36:52.745 [info] [Error - 18:36:52] Server initialization failed.
2023-10-13 18:36:52.745 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.745 [info] [Info  - 18:36:52] Connection to server got closed. Server will restart.
2023-10-13 18:36:52.745 [info] true
2023-10-13 18:36:52.745 [info] [Error - 18:36:52] Python Jedi client: couldn't create connection to server.
2023-10-13 18:36:52.745 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.776 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli

2023-10-13 18:36:52.776 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 18:36:52.779 [info] [Error - 18:36:52] Server initialization failed.
2023-10-13 18:36:52.779 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.779 [info] [Info  - 18:36:52] Connection to server got closed. Server will restart.
2023-10-13 18:36:52.779 [info] true
2023-10-13 18:36:52.779 [info] [Error - 18:36:52] Python Jedi client: couldn't create connection to server.
2023-10-13 18:36:52.779 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.779 [info] [Error - 18:36:52] Restarting server failed
2023-10-13 18:36:52.779 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.805 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 18:36:52.810 [info] [Error - 18:36:52] Server initialization failed.
2023-10-13 18:36:52.810 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.810 [info] [Info  - 18:36:52] Connection to server got closed. Server will restart.
2023-10-13 18:36:52.810 [info] true
2023-10-13 18:36:52.811 [info] [Error - 18:36:52] Python Jedi client: couldn't create connection to server.
2023-10-13 18:36:52.811 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.811 [info] [Error - 18:36:52] Restarting server failed
2023-10-13 18:36:52.811 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.834 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-13 18:36:52.834 [info]     from jedi_language_server.cli import cli

2023-10-13 18:36:52.835 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 18:36:52.847 [info] [Error - 18:36:52] Server initialization failed.
2023-10-13 18:36:52.847 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.847 [info] [Error - 18:36:52] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-13 18:36:52.847 [info] [Error - 18:36:52] Python Jedi client: couldn't create connection to server.
2023-10-13 18:36:52.847 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 18:36:52.847 [info] [Error - 18:36:52] Restarting server failed
2023-10-13 18:36:52.847 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
